keys:
  - &mac1chng age142e54afjeqajz4pgdc30tj8u6cjnyppj9ef3xjv4keqmk7pjcc2sfhk29x
  - &svr1chng age1w4tgfu8upwhpsm76sfuwls6f2suw6teurgz740lhv49v23h2scyqfzpmq7
  - &svr3chng age1nae8042a32y0qz8gefg09ff90meynyeqxr3tfgazjtajt4y0fa7seddw35
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mac1chng
          - *svr1chng
          - *svr3chng
