keys:
  - &mac1chng age142e54afjeqajz4pgdc30tj8u6cjnyppj9ef3xjv4keqmk7pjcc2sfhk29x
  - &dsk1chng age19u0znw92kpqp9q4lhm9g28sll0prjzuf2we3lcqjemnrk2vfnd9qwt68e6
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mac1chng
          - *dsk1chng
