keys:
  - &mac1chng age142e54afjeqajz4pgdc30tj8u6cjnyppj9ef3xjv4keqmk7pjcc2sfhk29x
  - &svr1chng age1w4tgfu8upwhpsm76sfuwls6f2suw6teurgz740lhv49v23h2scyqfzpmq7
  - &svr3chng age15fvgp98zudhkukru6qv2qcrv9s8q9a2vm8xpedq05je2j03l8c7szg9lwd
  - &dsk1chng age1xf27p02n2dvyazk44hr4hwcchza0888z3ezc282ysuwfwtfs7fxqytu7zj
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mac1chng
          - *svr1chng
          - *svr3chng
          - *dsk1chng
