---
# inspo: https://github.com/LGUG2Z/nixos-wsl-starter/blob/master/.github/workflows/build.yml
name: "Build tarball and ISO"
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}
  workflow_call: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v27

      - name: Build tarball
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin run .#nixosConfigurations.workchng.config.system.build.tarballBuilder

      - name: Build ISO
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin build .#nixosConfigurations.iso1chng.config.system.build.isoImage

      - name: Rename ISO
        run: sudo mv result/iso/nixos-*.iso nixos.iso

      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: nixos-wsl.tar.gz
          path: nixos-wsl.tar.gz

      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: nixos.iso
          path: nixos.iso

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nixos-wsl.tar.gz
            nixos.iso
